### ISSUE TITLE
Cannot run CassandraSimulation from sbt

### ISSUE THREAD

**Issue by vbachurin** [gatling-cql/GatlingCql#16]
I have included `GatlingCql-0.0.7.jar` into the classpath and the copy of `CassandraSimulation` `compile`s just fine. But when I run `test`, I get the following errors:

```
[IJ]> gatling-load/test
[info] Compiling 3 Scala sources to /Users/vbachurin/gatling-load/target/scala-2.11/test-classes...
[error] /Users/vbachurin/gatling-load/src/test/scala/load/CassandraSimulation.scala:11: object github is not a member of package io
[error] import io.github.gatling.cql.Predef._
[error]           ^
[error] /Users/vbachurin/gatling-load/src/test/scala/load/CassandraSimulation.scala:18: not found: value cql
[error]   val cqlConfig = cql.session(session) //Initialize Gatling DSL with your session
[error]                   ^
[error] /Users/vbachurin/gatling-load/src/test/scala/load/CassandraSimulation.scala:52: not found: value cql
[error]       .exec(cql("simple SELECT")
[error]             ^
[error] /Users/vbachurin/gatling-load/src/test/scala/load/CassandraSimulation.scala:56: not found: value cql
[error]       .exec(cql("prepared INSERT")
[error]             ^
[error] four errors found
[error] (gatling-load/test:compileIncremental) Compilation failed
[error] Total time: 5 s, completed Mar 25, 2018 1:40:14 PM
[IJ]> 
```

Am I missing something? 

If there a way to use GatlingCql not only using the Gatling script, would be great to have this described in the README.

Thanks!

**Comment by Mishail** [comment]
> Am I missing something?

Hard to say, but probably the class path for your tests is not configured properly 

> If there a way to use GatlingCql not only using the Gatling script, would be great to have this described in the README

You could generate a project using [Gatling Maven archetype](https://gatling.io/docs/2.3/extensions/maven_archetype/) and run your simulation from an IDE

**Comment by vbachurin** [comment]
> probably the class path for your tests is not configured properly

Indeed, previously I added the JAR only to the IDE project's classpath. But apparently that wasn't enough.
I have copied the JAR to the `$PROJECT_HOME/lib` and this did the job - the Cassandra simulation now works fine.
Thanks!
