### ISSUE TITLE
need example how to use checks with resultSet

### ISSUE THREAD

**Issue by ludenus** [gatling-cql/GatlingCql#17]
can someone please add more examples of how to log/validate resultSet

**Comment by Mishail** [comment]
You're probably looking for `check` functionality. There are quite a few examples in [CheckCompileTest](https://github.com/gatling-cql/GatlingCql/blob/master/src/test/scala/io/github/gatling/cql/CheckCompileTest.scala)

**Comment by ludenus** [comment]
Hi @Mishail 
[CheckCompileTest](https://github.com/gatling-cql/GatlingCql/blob/master/src/test/scala/io/github/gatling/cql/CheckCompileTest.scala) currently provides examples for **rowCount**, and I am asking about **resultSet**

**Comment by Mishail** [comment]
@ludenus I'm not quite get what do you need, 

```scala
              .check(exhausted is false,
                     rowCount is 1,
                     applied is false,
                     columnValue("str") is "foobar${sequenceNum}"
              ))
```

`check` provides you with a DSL to get information from a `ResultSet`, like to check its attributes (`exhausted`, `rowCount`, `applied`) and about colums and their values it contains (`columnValue`).

If you need something more exocotic you coud use `resultSet` and `transform` it to get a desired outcome. 

* `CqlCheck`s are defined here: https://github.com/gatling-cql/GatlingCql/blob/master/src/main/scala/io/github/gatling/cql/checks/CqlCheckSupport.scala

* They are implementation of a gatling `Check`: https://gatling.io/docs/current/http/http_check/#

**Comment by ludenus** [comment]
@Mishail 
thanks for reply
It is still not clear for me how to compare result of select *.. cql query with an expected result when the result contains multiple rows?
How to use this syntax for say 100 records?

```
.check(
    rowCount is 100,
    columnValue("str") is "foobar${sequenceNum}"
))
```

**Comment by Mishail** [comment]
@ludenus `validate` will allow you to use any arbitrary logic for your validation:

```scala
import io.gatling.commons.validation._
import io.gatling.core.check.Validator

...
...
        .check(resultSet.validate("resultSet", (actual, session) => actual match {
          case Some(r) =>
            if (r.wasApplied) actual.success // Just define your criteria and return actual.success if everything is good
            else "Sorry".failure // your criteria wasn't satisfied
          case None => Validator.FoundNothingFailure // nothing found
      }
...
...

```
https://gatling.io/docs/current/http/http_check/#http-check-validating

**Comment by Mishail** [comment]
We should implement something similar to `simpleCheck` in Gatling, which would accept a `CqlResponse => Boolean`

https://gatling.io/docs/current/jms/#jms-check-api
