### ISSUE TITLE
Deploy on maven central

### ISSUE THREAD

**Issue by slandelle** [gatling-cql/GatlingCql#23]
Hi @Mishail,

Your plugin is great. Then, I believe deploying it on maven central would ease usage and adoption for all maven/gradle/sbt users.

Regards

**Comment by Mishail** [comment]
- http://maven.apache.org/repository/guide-central-repository-upload.html
- https://github.com/simpligility/ossrh-demo
- https://central.sonatype.org/pages/requirements.html

**Comment by Mishail** [comment]
- [x] Request a name space - https://issues.sonatype.org/browse/OSSRH-56040
- [x] Attach sources
- [ ] Attach javadocs
- [ ] GPG signature
- [ ] Non-shaded jar

**Comment by Mishail** [comment]
Note for the future self: https://central.sonatype.org/pages/working-with-pgp-signatures.html#distributing-your-public-key

**Comment by Mishail** [comment]
@slandelle https://repo1.maven.org/maven2/io/github/gatling-cql/gatling-cql/3.3.1-2/

**Comment by slandelle** [comment]
Nice 👍
